CONFIG += no_fixpath
QT = charts core gui widgets
CONFIG += no_fixpath
QT = charts core gui widgets
CONFIG += no_fixpath
QT = charts core gui widgets
CONFIG += no_fixpath
QT = charts core gui widgets
CONFIG += no_fixpath
QT = charts core gui widgets
CONFIG += no_fixpath
QT = charts core gui widgets
