CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
CONFIG += no_fixpath
QT = charts core gui serialbus serialport widgets
