CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
CONFIG += no_fixpath
QT = core gui widgets serialbus serialport charts
